name: Pet Image Picker Web App

on:
  pull_request:
    branches: [ 'main' ]
  push:
    branches: [ '*' ]

jobs:
  eslint_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        working-directory: ./pet_image_picker
        run: npm install
      - name: Run ESLint
        working-directory: ./pet_image_picker
        run: npm run lint
  prettier_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        working-directory: ./pet_image_picker
        run: npm install
      - name: Run Prettier
        working-directory: ./pet_image_picker
        run: npm run format-check