name: Pet Image Classification Program

on:
  pull_request:
    branches: [ 'main' ]
  push:
    branches: [ '*' ]

jobs:
  black_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --diff"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          src: "*.py ml/*.py"
          use_pyproject: true
  pylint_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Pylint
        run: pip install pylint
      - name: Lint the backend program using pylint
        run: pylint *.py ml/*.py