name: Lint Codebase

on:
  pull_request:
    branches: [ 'main' ]
  push:
    branches: [ '*' ]

jobs:
  pylint_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Pylint
        run: pip install pylint
      - name: Lint the backend program using pylint
        run: pylint *.py ml/*.py